name: interface_app_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - flask
  - flask-cors
  - jupyter
  - matplotlib
  - langchain
  - langchain-community
  - langchainhub
  - ipykernel
  - numpy
  - pandas
  - python-dotenv
  - sqlalchemy
  - pip
  - pip:
    - cohere
    - langchain-cohere
    - langchainhub